sonar.projectKey=AnandThiru-5566_Software_Metrics
sonar.organization=anandthiru-5566

sonar.sources=.
sonar.tests=.
sonar.test.inclusions=test_*.py

sonar.exclusions=venv/**,htmlcov/**,__pycache__/**,.pytest_cache/**,catboost_info/**

sonar.python.coverage.reportPaths=coverage.xml

sonar.sourceEncoding=UTF-8