sonar.projectKey=AnandThiru-5566_Software_Metrics
sonar.organization=anandthiru-5566

sonar.sources=.
sonar.exclusions=test_*.py,venv/**,htmlcov/**,__pycache__/**,.pytest_cache/**,catboost_info/**

sonar.tests=.
sonar.test.inclusions=test_*.py

sonar.python.coverage.reportPaths=coverage.xml
sonar.sourceEncoding=UTF-8
